### ISSUE TITLE
Social Media - Design posts for Events/Days upto 31st October

### ISSUE THREAD

**Issue by tudims** [edwisely-ai/Marketing#54]
Calendar Postings : 

Let's create a theme and design posts @Saisree-gaddamwar 
As there are a lot of days postings let's split them into two chunks and work on them.
 
Looks like the second part has all the good days so let's finish the first part quickly :p.

Part 1 :

1. Ambedkar Jayanti
2. Rabindranath Tagore's Birthday
3. World Environment Day
4. Edwisely's Annual Day
5. World Social Media Day
6. International Friendship Day

Part 2:
7. International Youth Day
8. Independence Day
9. National Sports Day
10. Teachers’ Day
11. Engineers’ Day
12. Gandhi Jayanthi
13. World Mental Health Day

**Comment by kautilyabo** [comment]
Decided that it is a waste of our time to put wishes when we don't have the resources. 
Only spending time on Important Posts like Higher Education Posts.
