### ISSUE TITLE
Social Media - One Banner (Cover) Design for all Social Media Platforms 

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Marketing#62]

**Comment by tudims** [comment]
1. **Capitalize Most Words in Titles**
It is not wrong to do it @kautilyabo 
 https://www.grammarly.com/blog/capitalization-rules/

2. Spread the word to make people use the banner. You should start writing emails to the team for internal marketing. Write about what should be their email signature, their linkedin banners etc. 

3. Check out Harsha's linkedin banner. It is pretty powerful. Give that to few of our team mates. Make marketing exciting!!!!
