### ISSUE TITLE
SEO for NIRF website 

### ISSUE THREAD

**Issue by tudims** [edwisely-ai/Marketing#96]

**Comment by kautilyabo** [comment]
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/1a8748a5-bb17-45cd-8250-b7337900cf83)

**Comment by kautilyabo** [comment]
Desktop Suggestions : 
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/1a8748a5-bb17-45cd-8250-b7337900cf83)

Mobile Site Suggestions : 
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/6bf212f0-c6aa-496d-91a9-9b7c97eb0e1f)

Link : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fnirf.edwisely.com%2F&tab=mobile
