### ISSUE TITLE
Write blog articles on technical and non-technical NIRF Score Improvement 

### ISSUE THREAD

**Issue by tudims** [edwisely-ai/Marketing#97]

**Comment by kautilyabo** [comment]
Is there any better alternative to nirf rankings?
Why didn't my college get ranked by NIRF?
Research Beyond NIRF RP Parameter - Research Culture in India

**Comment by kautilyabo** [comment]
Is NIRF ranking reliable? 
Is there any better alternative to NIRF rankings?
Why didn't my college get ranked by NIRF?
Research Beyond NIRF RP Parameter - Research Culture in India
How to boost your NIRF ranking next year? 

"NIRF Ranking" - Keyword

**Comment by tudims** [comment]
Connect pandemic and NIRF ranking with one of the topics. And also number
the topics. We just need the top 6 blogs - 1000 words each. Will be able to
finish the writeups by May-end at any cost.

Thanks,
Yash




*Yashwanth Tudimilla *
Co-Founder, Edwisely

799 516 1950 | ***@***.*** ***@***.***>

www.edwisely.com | Skype: tudimilla

819/1, Manjeera Majestic Commercial,
JNTU Road, KPHB, Hyderabad -72

**Comment by kautilyabo** [comment]
All articles have separate issues created and are being tracked.
